version: '3.8'

services:
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: myproject
      POSTGRES_USER: myprojectuser
      POSTGRES_PASSWORD: password

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8001
    volumes:
      - .:/app
    ports:
      - "8000:8001"
    environment:
      - DEBUG=1
      - DJANGO_DB_NAME=myproject
      - DJANGO_DB_USER=myprojectuser
      - DJANGO_DB_PASSWORD=password
      - DJANGO_DB_HOST=db
    depends_on:
      - db
      - redis

  redis:
    image: redis:6

  celery:
    build: .
    command: celery -A myproject worker --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
    environment:
      - DJANGO_DB_NAME=myproject
      - DJANGO_DB_USER=myprojectuser
      - DJANGO_DB_PASSWORD=password
      - DJANGO_DB_HOST=db

volumes:
  postgres_data:
